name: Build for windows

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows:
    name: Build Windows x64
    runs-on: windows-2022
    
    steps:
      - name: configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.3
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"

      - name: Install python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install NASM
        shell: cmd
        run: choco install nasm -y

      - name: Build
        shell: cmd
        run: ./win/build.bat vcvars64

      - name: Copy all static libraries
        shell: cmd
        run: |
          mkdir all_libs
          copy deps\build\curl\lib\*.lib all_libs\ 2>nul
          copy deps\install\lib\*.lib all_libs\ 2>nul
          copy deps\install\lib\*.a all_libs\ 2>nul

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: curl-impersonate-windows-full
          path: |
            packages/bin/curl-impersonate.exe
            packages/bin/*.bat
            packages/include/curl/*.h
            all_libs/*.lib
            all_libs/*.a
            packages/LICENSE*
