name: Build Windows Custom

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows-x64:
    name: Build Windows x64
    runs-on: windows-2022
    
    steps:
      - name: configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.3
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"

      - name: Install python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install NASM
        shell: cmd
        run: choco install nasm -y

      - name: Build x64
        shell: cmd
        run: ./win/build.bat vcvars64

      - name: Copy x64 artifacts
        shell: cmd
        run: |
          mkdir artifacts_x64
          if exist packages\bin\curl-impersonate.exe copy packages\bin\curl-impersonate.exe artifacts_x64\
          if exist packages\bin\*.bat copy packages\bin\*.bat artifacts_x64\
          if exist packages\include\curl xcopy /E /I packages\include\curl artifacts_x64\include\curl\
          if exist packages\lib\*.lib copy packages\lib\*.lib artifacts_x64\
          if exist packages\*.LICENSE* copy packages\*.LICENSE* artifacts_x64\

      - name: Upload x64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: curl-impersonate-windows-x64-full
          path: artifacts_x64/*

  build-windows-x86:
    name: Build Windows x86
    runs-on: windows-2022
    
    steps:
      - name: configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.3
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"

      - name: Install python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install NASM
        shell: cmd
        run: choco install nasm -y

      - name: Build x86
        shell: cmd
        run: ./win/build.bat vcvars32

      - name: Copy x86 artifacts
        shell: cmd
        run: |
          mkdir artifacts_x86
          if exist packages\bin\curl-impersonate.exe copy packages\bin\curl-impersonate.exe artifacts_x86\
          if exist packages\bin\*.bat copy packages\bin\*.bat artifacts_x86\
          if exist packages\include\curl xcopy /E /I packages\include\curl artifacts_x86\include\curl\
          if exist packages\lib\*.lib copy packages\lib\*.lib artifacts_x86\
          if exist packages\*.LICENSE* copy packages\*.LICENSE* artifacts_x86\

      - name: Upload x86 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: curl-impersonate-windows-x86-full
          path: artifacts_x86/*
